name: Process Earthquake Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  process-earthquake-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Invoke Lambda function
      run: |
        aws lambda invoke \
          --function-name ProcessEarthquakeData \
          --payload '{}' \
          response.json
        
        echo "Lambda response:"
        cat response.json
        
    - name: Check if Lambda succeeded
      run: |
        if grep -q '"errorMessage"' response.json; then
          echo "Lambda function failed!"
          cat response.json
          exit 1
        else
          echo "Lambda function succeeded!"
        fi
